name: Deploy to AWS Lightsail

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to Lightsail
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        port: 22
        script: |
          # Navigate to CMS directory
          cd /home/ubuntu/cms
          
          # Pull latest code (if using git)
          if [ -d ".git" ]; then
            git pull origin main
          else
            # First time setup - clone the repository
            cd /home/ubuntu
            rm -rf cms
            git clone https://github.com/${{ github.repository }}.git cms
            cd cms
          fi
          
          # Install dependencies
          npm install
          
          # Create .env file if it doesn't exist
          if [ ! -f .env ]; then
            cat > .env << 'EOF'
NODE_ENV=production
HOST=0.0.0.0
PORT=1337
APP_KEYS=${{ secrets.STRAPI_APP_KEYS }}
API_TOKEN_SALT=${{ secrets.STRAPI_API_TOKEN_SALT }}
ADMIN_JWT_SECRET=${{ secrets.STRAPI_ADMIN_JWT_SECRET }}
TRANSFER_TOKEN_SALT=${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }}
JWT_SECRET=${{ secrets.STRAPI_JWT_SECRET }}

DATABASE_CLIENT=postgres
DATABASE_HOST=localhost
DATABASE_PORT=5432
DATABASE_NAME=strapidb
DATABASE_USERNAME=strapiuser
DATABASE_PASSWORD=CompleoHealth2024
DATABASE_SSL=false
EOF
          fi
          
          # Build Strapi
          npm run build
          
          # Restart with PM2
          pm2 delete strapi-cms 2>/dev/null || true
          pm2 start npm --name "strapi-cms" -- start
          pm2 save
          
          # Show status
          pm2 status